# Site wide configuration

title: "Geek Diva's Blog"
description: "Technology, coaching, beauty, everyday life... and everything in between."
logo: logo.jpg
teaser: teaser.jpg
locale: en
url: http://geekdiva.blog
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Erika Vilches
  email:
  twitter: evilches
  google:
    ad-client:
    ad-slot:
  bio: "@Microsoft | BS in Computer Science and Engineering | MSc in Artificial Intelligence | PhD Candidate | Happily married"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: erikavilches

 # Octopress Configuration
# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft 
  
include:
  - .htaccess
  -  ["_pages"]
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
